site:
  component: '@sls-next/serverless-component'
  inputs:
    roleArn: arn:aws:iam::960028696012:role/bingoalApp

UsersTable:
  component: '@serverless/aws-dynamodb'
  inputs:
    name: Users

UsersSessionsTable:
  component: '@serverless/aws-dynamodb'
  inputs:
    name: UsersSessions
    attributeDefinitions:
      - AttributeName: fixtureId
        AttributeType: S
      - AttributeName: userId
        AttributeType: S
    keySchema:
      - AttributeName: fixtureId
        KeyType: HASH
      - AttributeName: userId
        KeyType: RANGE
